import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Poppins, DM_Sans } from "next/font/google";

const poppins_init = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins'
})

const dm_sans_init = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-dm_sans'
})


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins_init.variable} ${dm_sans_init.variable}`}>{children}</body>
    </html>
  );
}
